# Generated by Django 4.2.2 on 2023-07-06 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0003_farm_average_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farm',
            new_name='Hotel',
        ),
    ]
