# Generated by Django 4.2.2 on 2023-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_rename_food_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
